#!/usr/bin/env python3
"""Generate the static SVG figures for jc2.fun.

Every curve here is computed from the map or equation it illustrates, so the
pictures can be regenerated and checked rather than trusted.  Output goes to
src/components/figures/*.astro.  Run:  python3 scripts/figures.py
"""
from __future__ import annotations

import math
import pathlib

OUT = pathlib.Path(__file__).resolve().parent.parent / "src" / "figures"
W = 640  # text-measure figures
WIDE = 880


class Frame:
    """Maps mathematical coordinates into a rectangle of the SVG canvas."""

    def __init__(self, xr, yr, box):
        (self.x0, self.x1), (self.y0, self.y1) = xr, yr
        self.px, self.py, self.pw, self.ph = box

    def __call__(self, x, y):
        u = self.px + (x - self.x0) / (self.x1 - self.x0) * self.pw
        v = self.py + self.ph - (y - self.y0) / (self.y1 - self.y0) * self.ph
        return u, v

    def path(self, pts, close=False):
        d = []
        for i, (x, y) in enumerate(pts):
            u, v = self(x, y)
            d.append(f"{'M' if i == 0 else 'L'}{u:.2f} {v:.2f}")
        if close:
            d.append("Z")
        return "".join(d)


def lin(a, b, n=160):
    return [a + (b - a) * i / (n - 1) for i in range(n)]


def svg(width, height, body, extra=""):
    return (
        f'<svg viewBox="0 0 {width} {height}" xmlns="http://www.w3.org/2000/svg" '
        f'aria-hidden="true" focusable="false"{extra}>\n{body}\n</svg>'
    )


# Rough advance widths, in px per character, for the fonts the figures use.
_ADVANCE = {"": 6.3, "ttl": 8.4, "math": 6.6}


def lint(name, markup, width):
    """Warn when a generated label would be clipped or would overlap a panel."""
    import re as _re

    problems = []
    for m in _re.finditer(r'<text class="([^"]*)" x="([\d.]+)" y="([\d.]+)">([^<]*)</text>'
                          r'|<text x="([\d.]+)" y="([\d.]+)" class="([^"]*)">([^<]*)</text>', markup):
        if m.group(4) is not None:
            cls, x, y, text = m.group(1), float(m.group(2)), float(m.group(3)), m.group(4)
        else:
            cls, x, y, text = m.group(7), float(m.group(5)), float(m.group(6)), m.group(8)
        kind = "ttl" if "ttl" in cls else ("math" if "math" in cls else "")
        end = x + len(text) * _ADVANCE[kind]
        if end > width - 4:
            problems.append(f"    overruns canvas by {end - width:.0f}px: {text!r}")
        elif y < 60 and x < 340 and end > 366 and width == W:
            # Only the heading band has a right-hand neighbour; full-width
            # footer lines below the panels are fine.
            problems.append(f"    runs into the right panel's heading: {text!r}")
    for p in problems:
        print(f"  ! {name}:\n{p}")
    return not problems


def write(name, description, markup):
    """Emit a bare SVG, inlined into the prose by src/lib/remark-figure.mjs."""
    OUT.mkdir(parents=True, exist_ok=True)
    header = f"<!-- Generated by scripts/figures.py. {description} -->\n"
    width = W if f'viewBox="0 0 {W} ' in markup else WIDE
    ok = lint(name, markup, width)
    (OUT / f"{name}.svg").write_text(header + markup + "\n")
    print(f"  wrote {name}.svg{'' if ok else '  (see warnings above)'}")


# --------------------------------------------------------------------------
# 1. A shear: (x, y) -> (x + y^2, y).  Nonlinear, yet undone exactly.
# --------------------------------------------------------------------------
def fig_shear():
    h = 300
    xr, yr = (-2.2, 4.6), (-1.7, 1.7)
    pw, ph = 285, 200
    left = Frame(xr, yr, (14, 58, pw, ph))
    right = Frame(xr, yr, (341, 58, pw, ph))
    out = []

    def panel(fr, sheared, title, sub):
        g = [f'<text class="lbl-ink ttl" x="{fr.px}" y="30">{title}</text>',
             f'<text x="{fr.px}" y="46">{sub}</text>']
        # Axes.
        g.append(f'<path class="axis" d="{fr.path([(xr[0], 0), (xr[1], 0)])}"/>')
        g.append(f'<path class="axis" d="{fr.path([(0, yr[0]), (0, yr[1])])}"/>')

        def img(x, y):
            return (x + y * y, y) if sheared else (x, y)

        # Vertical lines x = c become the parabolas x = c + y^2.
        c = -2.0
        while c <= 2.001:
            pts = [img(c, t) for t in lin(-1.5, 1.5)]
            pts = [p for p in pts if xr[0] <= p[0] <= xr[1]]
            if len(pts) > 1:
                g.append(f'<path class="grid" d="{fr.path(pts)}"/>')
            c += 0.5
        # Horizontal lines y = c slide sideways but stay straight.
        c = -1.5
        while c <= 1.501:
            pts = [img(t, c) for t in lin(-2.0, 2.0, 60)]
            pts = [p for p in pts if xr[0] <= p[0] <= xr[1]]
            if len(pts) > 1:
                g.append(f'<path class="grid" d="{fr.path(pts)}"/>')
            c += 0.5
        # Two tracked points.
        for (x, y), lbl in (((-1.0, 1.0), "a"), ((1.0, -1.5), "b")):
            u, v = fr(*img(x, y))
            g.append(f'<circle class="dot" cx="{u:.2f}" cy="{v:.2f}" r="3.6"/>')
            g.append(f'<text class="lbl-mark math" x="{u + 7:.2f}" y="{v - 6:.2f}">{lbl}</text>')
        return "\n".join(g)

    out.append(panel(left, False, "before", "the plane, ruled by a unit grid"))
    out.append(panel(right, True, "after", "the image under (x, y) ↦ (x + y², y)"))
    # Arrow between the panels.
    out.append('<path class="arrow" d="M308 158 L332 158"/>')
    out.append('<path class="arrowhead" d="M332 158 l-6 -3.4 v6.8 Z"/>')
    out.append('<text class="lbl-mark" x="303" y="148">F</text>')
    write(
        "shear-grid",
        "A unit grid and its image under the shear (x, y) -> (x + y^2, y).",
        svg(W, h, "\n".join(out)),
    )


# --------------------------------------------------------------------------
# 2. E(s,t) = (e^s cos t, e^s sin t): locally reversible, globally many-to-one.
# --------------------------------------------------------------------------
def fig_wrap():
    h = 312
    out = []
    # Exactly three whole strips, so every band is the same height.
    T0, T1 = -math.pi, 5 * math.pi
    left = Frame((-2.4, 2.4), (T0, T1), (56, 62, 210, 206))
    right = Frame((-2.9, 2.9), (-2.9, 2.9), (372, 62, 210, 206))

    out.append('<text class="lbl-ink ttl" x="56" y="32">domain</text>')
    out.append('<text x="56" y="48">(s, t), in strips of height 2π</text>')
    out.append('<text class="lbl-ink ttl" x="372" y="32">image</text>')
    out.append('<text x="372" y="48">the punctured plane</text>')

    for k, base in enumerate((-math.pi, math.pi, 3 * math.pi)):
        top = base + 2 * math.pi
        pts = [(-2.4, base), (2.4, base), (2.4, top), (-2.4, top)]
        out.append(f'<path class="{"strip-a" if k % 2 == 0 else "strip-b"}" d="{left.path(pts, close=True)}"/>')
        u, v = left(-2.2, (base + top) / 2)
        out.append(f'<text x="{u:.1f}" y="{v:.1f}" class="lbl-faint">k={k}</text>')

    out.append(f'<path class="axis" d="{left.path([(-2.4, 0), (2.4, 0)])}"/>')
    out.append(f'<path class="axis" d="{left.path([(0, T0), (0, T1)])}"/>')
    out.append(f'<text class="math lbl-ink" x="{left(2.02, 0)[0]:.1f}" y="{left(0, 0)[1] - 7:.1f}">s</text>')
    out.append(f'<text class="math lbl-ink" x="{left(0, 0)[0] + 7:.1f}" y="{left(0, T1 - 0.7)[1]:.1f}">t</text>')

    for r in (0.6, 1.2, 1.9, 2.6):
        pts = [(r * math.cos(a), r * math.sin(a)) for a in lin(0, 2 * math.pi)]
        out.append(f'<path class="grid" d="{right.path(pts, close=True)}"/>')
    for k in range(12):
        a = k * math.pi / 6
        out.append(f'<path class="grid" d="{right.path([(0.25*math.cos(a), 0.25*math.sin(a)), (2.75*math.cos(a), 2.75*math.sin(a))])}"/>')
    ou, ov = right(0, 0)
    out.append(f'<circle class="puncture" cx="{ou:.2f}" cy="{ov:.2f}" r="4"/>')
    out.append(f'<text class="lbl-faint" x="{right(-2.75, -2.55)[0]:.1f}" y="{right(0, -2.55)[1]:.1f}">origin omitted</text>')

    # One patch, drawn twice in the domain a full strip apart, once in the image.
    s0, ds, t0, dt = 0.35, 0.22, 1.15, 0.45
    for t in (t0, t0 + 2 * math.pi):
        pts = [(s0 - ds, t - dt), (s0 + ds, t - dt), (s0 + ds, t + dt), (s0 - ds, t + dt)]
        out.append(f'<path class="patch" d="{left.path(pts, close=True)}"/>')
    ring = []
    for i, sv in enumerate((s0 - ds, s0 + ds)):
        arc = [(math.exp(sv) * math.cos(t), math.exp(sv) * math.sin(t)) for t in lin(t0 - dt, t0 + dt, 28)]
        ring += arc if i == 0 else arc[::-1]
    out.append(f'<path class="patch" d="{right.path(ring, close=True)}"/>')

    out.append('<path class="arrow" d="M292 168 L346 168"/>')
    out.append('<path class="arrowhead" d="M346 168 l-6 -3.4 v6.8 Z"/>')
    out.append('<text class="lbl-mark math" x="310" y="160">E</text>')
    out.append(f'<text class="lbl-mark" x="56" y="{h - 12}">the two marked patches lie 2π apart and share one image</text>')

    write(
        "exponential-wrap",
        "Strips of height 2pi in the (s,t) plane wrapping onto the punctured plane under E.",
        svg(W, h, "\n".join(out)),
    )


# --------------------------------------------------------------------------
# 3. H(x, y) = (x, xy): the input escapes while the output converges.
# --------------------------------------------------------------------------
def fig_escape():
    h = 300
    out = []
    left = Frame((-0.35, 3.4), (-0.6, 6.4), (56, 58, 215, 200))
    right = Frame((-0.35, 3.4), (-0.6, 2.4), (372, 58, 215, 200))

    out.append('<text class="lbl-ink ttl" x="56" y="30">input</text>')
    out.append('<text x="56" y="46">the path (1/t, t) runs off to infinity</text>')
    out.append('<text class="lbl-ink ttl" x="372" y="30">output</text>')
    out.append('<text x="372" y="46">its image settles on a finite point</text>')

    for fr, ymax in ((left, 6.4), (right, 2.4)):
        out.append(f'<path class="axis" d="{fr.path([(-0.35, 0), (3.4, 0)])}"/>')
        out.append(f'<path class="axis" d="{fr.path([(0, -0.6), (0, ymax)])}"/>')

    # Input path: x = 1/t, y = t, for t in [0.32, 6.2].
    pts = [(1 / t, t) for t in lin(0.32, 6.2, 260)]
    pts = [(x, y) for x, y in pts if x <= 3.4 and y <= 6.4]
    out.append(f'<path class="curve" d="{left.path(pts)}"/>')
    for t in (0.9, 1.6, 2.8, 5.0):
        u, v = left(1 / t, t)
        out.append(f'<circle class="dot" cx="{u:.2f}" cy="{v:.2f}" r="3.1"/>')
    out.append(f'<text class="math lbl-mark" x="{left(0.55, 4.6)[0]:.1f}" y="{left(0.55, 4.6)[1]:.1f}">xy = 1</text>')

    # Output path: the horizontal segment v = 1, marching toward (0, 1).
    out.append(f'<path class="curve" d="{right.path([(1 / 0.32, 1), (1 / 6.2, 1)])}"/>')
    for t in (0.9, 1.6, 2.8, 5.0):
        u, v = right(min(1 / t, 3.4), 1)
        out.append(f'<circle class="dot" cx="{u:.2f}" cy="{v:.2f}" r="3.1"/>')
    au, av = right(0, 1)
    out.append(f'<circle class="open" cx="{au:.2f}" cy="{av:.2f}" r="4.6"/>')
    out.append(f'<text class="lbl-mark" x="{au + 9:.1f}" y="{av - 18:.1f}">asymptotic value (0, 1)</text>')

    out.append('<path class="arrow" d="M292 158 L352 158"/>')
    out.append('<path class="arrowhead" d="M352 158 l-6 -3.4 v6.8 Z"/>')
    out.append('<text class="lbl-mark math" x="310" y="150">H</text>')
    out.append(f'<text class="lbl-faint" x="56" y="{h - 14}">not a Keller map — the Jacobian of H is x, which vanishes along a line</text>')

    write(
        "escape-to-infinity",
        "The path (1/t, t) escaping to infinity while its image under H(x,y)=(x,xy) converges to (0,1).",
        svg(W, h, "\n".join(out)),
    )


# --------------------------------------------------------------------------
# 4. Monodromy: the two roots of z^2 = w exchange as w circles the origin.
# --------------------------------------------------------------------------
def fig_monodromy():
    h = 322
    out = []
    left = Frame((-1.7, 1.7), (-1.7, 1.7), (56, 62, 200, 200))
    right = Frame((-1.9, 1.9), (-1.4, 1.4), (360, 62, 230, 200))

    out.append('<text class="lbl-ink ttl" x="56" y="30">an ordinary branch point</text>')
    out.append('<text x="56" y="46">carrying w once around 0 swaps the roots of z² = w</text>')
    out.append('<text class="lbl-ink ttl" x="360" y="30">the hypothetical Keller picture</text>')
    out.append('<text x="360" y="46">the obstacle is the asymptotic curve, not a finite point</text>')

    out.append(f'<path class="axis" d="{left.path([(-1.7, 0), (1.7, 0)])}"/>')
    out.append(f'<path class="axis" d="{left.path([(0, -1.7), (0, 1.7)])}"/>')

    # The two square roots, traced over a half turn each while w does a full turn.
    r = 1.0
    for sign, cls in ((1, "curve"), (-1, "curve-alt")):
        pts = [(sign * math.sqrt(r) * math.cos(a / 2), sign * math.sqrt(r) * math.sin(a / 2))
               for a in lin(0, 2 * math.pi, 120)]
        out.append(f'<path class="{cls}" d="{left.path(pts)}"/>')
        su, sv = left(*pts[0])
        eu, ev = left(*pts[-1])
        out.append(f'<circle class="dot" cx="{su:.2f}" cy="{sv:.2f}" r="3.4"/>')
        out.append(f'<circle class="open" cx="{eu:.2f}" cy="{ev:.2f}" r="4"/>')
    out.append(f'<text class="math lbl-ink" x="{left(1.12, 0.14)[0]:.1f}" y="{left(1.12, 0.14)[1]:.1f}">+√w</text>')
    out.append(f'<text class="math lbl-ink" x="{left(-1.5, -0.22)[0]:.1f}" y="{left(-1.5, -0.22)[1]:.1f}">−√w</text>')
    bu, bv = left(0, 0)
    out.append(f'<circle class="puncture" cx="{bu:.2f}" cy="{bv:.2f}" r="4"/>')

    # Right: an asymptotic curve, a loop around it, and N inverse sheets above.
    curve = [(t, 0.28 * math.sin(1.5 * t) - 0.45) for t in lin(-1.85, 1.85)]
    out.append(f'<path class="curve-heavy" d="{right.path(curve)}"/>')
    out.append(f'<text class="lbl-mark" x="{right(-1.8, -0.95)[0]:.1f}" y="{right(-1.8, -0.95)[1]:.1f}">the non-properness set</text>')
    loop = [(0.55 + 0.34 * math.cos(a), -0.36 + 0.22 * math.sin(a)) for a in lin(0, 2 * math.pi)]
    out.append(f'<path class="loop" d="{right.path(loop, close=True)}"/>')
    for k in range(4):
        yy = 0.42 + 0.24 * k
        arc = [(t, yy + 0.05 * math.sin(2.2 * t)) for t in lin(-0.1, 1.25, 40)]
        out.append(f'<path class="sheet" d="{right.path(arc)}"/>')
    out.append(f'<text class="lbl-faint" x="{right(1.32, 0.95)[0]:.1f}" y="{right(1.32, 0.95)[1]:.1f}">N sheets</text>')
    out.append(f'<text class="lbl-faint" x="{right(-1.85, 1.15)[0]:.1f}" y="{right(-1.85, 1.15)[1]:.1f}">local inverses over the loop</text>')

    write(
        "monodromy",
        "Root exchange for z^2 = w beside a schematic of inverse sheets over a loop around the asymptotic curve.",
        svg(W, h, "\n".join(out)),
    )


# --------------------------------------------------------------------------
# 5. The Newton polygon of y^2 - x^3 - x, and the curve it predicts.
# --------------------------------------------------------------------------
def fig_newton():
    h = 336
    out = []
    left = Frame((-0.55, 3.6), (-0.55, 2.6), (96, 66, 285, 190))
    right = Frame((-1.4, 3.1), (-6.0, 6.0), (510, 66, 285, 190))

    out.append('<text class="lbl-ink ttl" x="96" y="32">exponents</text>')
    out.append('<text x="96" y="48">the monomials of y² − x³ − x, and their hull</text>')
    out.append('<text class="lbl-ink ttl" x="510" y="32">the curve</text>')
    out.append('<text x="510" y="48">a real slice of y² = x³ + x, against y = ±x^{3/2}</text>')

    # Lattice.
    for i in range(4):
        for j in range(3):
            u, v = left(i, j)
            out.append(f'<circle class="lattice" cx="{u:.2f}" cy="{v:.2f}" r="1.4"/>')
    out.append(f'<path class="axis" d="{left.path([(-0.4, 0), (3.5, 0)])}"/>')
    out.append(f'<path class="axis" d="{left.path([(0, -0.4), (0, 2.5)])}"/>')
    out.append(f'<text class="math lbl-ink" x="{left(3.4, 0)[0]:.1f}" y="{left(0, 0)[1] + 20:.1f}">i</text>')
    out.append(f'<text class="math lbl-ink" x="{left(0, 0)[0] - 18:.1f}" y="{left(0, 2.4)[1]:.1f}">j</text>')

    # Hull of {(0,2), (3,0), (1,0)}.
    hull = [(0, 2), (3, 0), (1, 0)]
    out.append(f'<path class="hull" d="{left.path(hull, close=True)}"/>')
    # The edge that sets the balance 2r = 3.
    out.append(f'<path class="edge" d="{left.path([(0, 2), (3, 0)])}"/>')
    for (i, j), lbl in (((0, 2), "y²"), ((3, 0), "x³"), ((1, 0), "x")):
        u, v = left(i, j)
        out.append(f'<circle class="dot" cx="{u:.2f}" cy="{v:.2f}" r="4.2"/>')
        out.append(f'<text class="math lbl-ink" x="{u + 9:.1f}" y="{v - 8:.1f}">{lbl}</text>')
    mu, mv = left(1.5, 1.0)
    out.append(f'<text class="lbl-mark" x="{mu + 12:.1f}" y="{mv - 4:.1f}">slope −⅔ → r = 3/2</text>')

    # The curve y^2 = x^3 + x, real slice, and its leading approximation.
    upper = [(x, math.sqrt(x ** 3 + x)) for x in lin(0, 3.05, 300)]
    out.append(f'<path class="curve-heavy" d="{right.path(upper)}"/>')
    out.append(f'<path class="curve-heavy" d="{right.path([(x, -y) for x, y in upper])}"/>')
    approx = [(x, x ** 1.5) for x in lin(0, 3.05, 300)]
    out.append(f'<path class="dashed" d="{right.path(approx)}"/>')
    out.append(f'<path class="dashed" d="{right.path([(x, -y) for x, y in approx])}"/>')
    out.append(f'<path class="axis" d="{right.path([(-1.3, 0), (3.05, 0)])}"/>')
    out.append(f'<path class="axis" d="{right.path([(0, -5.8), (0, 5.8)])}"/>')
    out.append(f'<text class="math lbl-ink" x="{right(2.05, 4.45)[0]:.1f}" y="{right(2.05, 4.45)[1]:.1f}">y² = x³ + x</text>')
    out.append(f'<text class="lbl-mark math" x="{right(1.55, -4.3)[0]:.1f}" y="{right(1.55, -4.3)[1]:.1f}">y = ±x^(3/2)</text>')
    out.append(f'<text class="lbl-faint" x="510" y="{h - 14}">the two agree to leading order and separate below it</text>')

    write(
        "newton-polygon",
        "The Newton polygon of y^2 - x^3 - x beside the real slice of the curve and its leading approximation.",
        svg(WIDE, h, "\n".join(out), extra=' preserveAspectRatio="xMidYMid meet"'),
    )


if __name__ == "__main__":
    print("generating figures ->", OUT)
    fig_shear()
    fig_wrap()
    fig_escape()
    fig_monodromy()
    fig_newton()
