#!/usr/bin/env python3
"""Generate the static SVG figures for jc2.fun.

Every curve here is computed from the map or equation it illustrates, so the
pictures can be regenerated and checked rather than trusted.  Output goes to
src/components/figures/*.astro.  Run:  python3 scripts/figures.py
"""
from __future__ import annotations

import math
import pathlib

OUT = pathlib.Path(__file__).resolve().parent.parent / "src" / "figures"
W = 640  # text-measure figures
WIDE = 880


class Frame:
    """Maps mathematical coordinates into a rectangle of the SVG canvas."""

    def __init__(self, xr, yr, box):
        (self.x0, self.x1), (self.y0, self.y1) = xr, yr
        self.px, self.py, self.pw, self.ph = box

    def __call__(self, x, y):
        u = self.px + (x - self.x0) / (self.x1 - self.x0) * self.pw
        v = self.py + self.ph - (y - self.y0) / (self.y1 - self.y0) * self.ph
        return u, v

    def path(self, pts, close=False):
        d = []
        for i, (x, y) in enumerate(pts):
            u, v = self(x, y)
            d.append(f"{'M' if i == 0 else 'L'}{u:.2f} {v:.2f}")
        if close:
            d.append("Z")
        return "".join(d)


def lin(a, b, n=160):
    return [a + (b - a) * i / (n - 1) for i in range(n)]


def heading(x, title, subtitle):
    """A panel's title and one-line subtitle, in the standard position."""
    return [
        f'<text class="lbl-ink ttl" x="{x}" y="30">{title}</text>',
        f'<text x="{x}" y="46">{subtitle}</text>',
    ]


def footnote(x, h, text):
    """The faint closing line along the bottom of a figure."""
    return f'<text class="lbl-faint" x="{x}" y="{h - 14}">{text}</text>'


def svg(width, height, body, extra=""):
    return (
        f'<svg viewBox="0 0 {width} {height}" xmlns="http://www.w3.org/2000/svg" '
        f'aria-hidden="true" focusable="false"{extra}>\n{body}\n</svg>'
    )


# Rough advance widths, in px per character, for the fonts the figures use.
_ADVANCE = {"": 6.6, "ttl": 8.6, "math": 6.8}


def lint(name, markup, width):
    """Warn when a generated label would be clipped or would overlap a panel."""
    import re as _re

    problems = []
    for m in _re.finditer(r'<text class="([^"]*)" x="([\d.]+)" y="([\d.]+)">([^<]*)</text>'
                          r'|<text x="([\d.]+)" y="([\d.]+)" class="([^"]*)">([^<]*)</text>'
                          r'|<text x="([\d.]+)" y="([\d.]+)">([^<]*)</text>', markup):
        if m.group(4) is not None:
            cls, x, y, text = m.group(1), float(m.group(2)), float(m.group(3)), m.group(4)
        elif m.group(8) is not None:
            cls, x, y, text = m.group(7), float(m.group(5)), float(m.group(6)), m.group(8)
        else:
            cls, x, y, text = "", float(m.group(9)), float(m.group(10)), m.group(11)
        kind = "ttl" if "ttl" in cls else ("math" if "math" in cls else "")
        end = x + len(text) * _ADVANCE[kind]
        if end > width - 4:
            problems.append(f"    overruns canvas by {end - width:.0f}px: {text!r}")
        elif y < 60 and x < 340 and end > 366 and width == W:
            # Only the heading band has a right-hand neighbour; full-width
            # footer lines below the panels are fine.
            problems.append(f"    runs into the right panel's heading: {text!r}")
    for p in problems:
        print(f"  ! {name}:\n{p}")
    return not problems


def write(name, description, markup):
    """Emit a bare SVG, inlined into the prose by src/lib/remark-figure.mjs."""
    OUT.mkdir(parents=True, exist_ok=True)
    header = f"<!-- Generated by scripts/figures.py. {description} -->\n"
    width = W if f'viewBox="0 0 {W} ' in markup else WIDE
    ok = lint(name, markup, width)
    (OUT / f"{name}.svg").write_text(header + markup + "\n")
    print(f"  wrote {name}.svg{'' if ok else '  (see warnings above)'}")


# --------------------------------------------------------------------------
# 1. A shear: (x, y) -> (x + y^2, y).  Nonlinear, yet undone exactly.
# --------------------------------------------------------------------------
def fig_shear():
    h = 300
    xr, yr = (-2.2, 4.6), (-1.7, 1.7)
    pw, ph = 285, 200
    left = Frame(xr, yr, (14, 58, pw, ph))
    right = Frame(xr, yr, (341, 58, pw, ph))
    out = []

    def panel(fr, sheared, title, sub):
        g = heading(fr.px, title, sub)
        # Axes.
        g.append(f'<path class="axis" d="{fr.path([(xr[0], 0), (xr[1], 0)])}"/>')
        g.append(f'<path class="axis" d="{fr.path([(0, yr[0]), (0, yr[1])])}"/>')

        def img(x, y):
            return (x + y * y, y) if sheared else (x, y)

        # Vertical lines x = c become the parabolas x = c + y^2.
        c = -2.0
        while c <= 2.001:
            pts = [img(c, t) for t in lin(-1.5, 1.5)]
            pts = [p for p in pts if xr[0] <= p[0] <= xr[1]]
            if len(pts) > 1:
                g.append(f'<path class="grid" d="{fr.path(pts)}"/>')
            c += 0.5
        # Horizontal lines y = c slide sideways but stay straight.
        c = -1.5
        while c <= 1.501:
            pts = [img(t, c) for t in lin(-2.0, 2.0, 60)]
            pts = [p for p in pts if xr[0] <= p[0] <= xr[1]]
            if len(pts) > 1:
                g.append(f'<path class="grid" d="{fr.path(pts)}"/>')
            c += 0.5
        # Two tracked points.
        for (x, y), lbl in (((-1.0, 1.0), "a"), ((1.0, -1.5), "b")):
            u, v = fr(*img(x, y))
            g.append(f'<circle class="dot" cx="{u:.2f}" cy="{v:.2f}" r="3.6"/>')
            g.append(f'<text class="lbl-mark math" x="{u + 7:.2f}" y="{v - 6:.2f}">{lbl}</text>')
        return "\n".join(g)

    out.append(panel(left, False, "before", "the plane, ruled by a unit grid"))
    out.append(panel(right, True, "after", "the image under (x, y) ↦ (x + y², y)"))
    # Arrow between the panels.
    out.append('<path class="arrow" d="M308 158 L332 158"/>')
    out.append('<path class="arrowhead" d="M332 158 l-6 -3.4 v6.8 Z"/>')
    out.append('<text class="lbl-mark" x="303" y="148">F</text>')
    write(
        "shear-grid",
        "A unit grid and its image under the shear (x, y) -> (x + y^2, y).",
        svg(W, h, "\n".join(out)),
    )


# --------------------------------------------------------------------------
# 2. E(s,t) = (e^s cos t, e^s sin t): locally reversible, globally many-to-one.
# --------------------------------------------------------------------------
def fig_wrap():
    h = 312
    out = []
    # Exactly three whole strips, so every band is the same height.
    T0, T1 = -math.pi, 5 * math.pi
    left = Frame((-2.4, 2.4), (T0, T1), (56, 62, 210, 206))
    right = Frame((-2.9, 2.9), (-2.9, 2.9), (372, 62, 210, 206))

    out += heading(56, 'domain', '(s, t), in strips of height 2 pi')
    out += heading(372, 'image', 'the punctured plane')

    for k, base in enumerate((-math.pi, math.pi, 3 * math.pi)):
        top = base + 2 * math.pi
        pts = [(-2.4, base), (2.4, base), (2.4, top), (-2.4, top)]
        out.append(f'<path class="{"strip-a" if k % 2 == 0 else "strip-b"}" d="{left.path(pts, close=True)}"/>')
        u, v = left(-2.2, (base + top) / 2)
        out.append(f'<text x="{u:.1f}" y="{v:.1f}" class="lbl-faint">k={k}</text>')

    out.append(f'<path class="axis" d="{left.path([(-2.4, 0), (2.4, 0)])}"/>')
    out.append(f'<path class="axis" d="{left.path([(0, T0), (0, T1)])}"/>')
    out.append(f'<text class="math lbl-ink" x="{left(2.02, 0)[0]:.1f}" y="{left(0, 0)[1] - 7:.1f}">s</text>')
    out.append(f'<text class="math lbl-ink" x="{left(0, 0)[0] + 7:.1f}" y="{left(0, T1 - 0.7)[1]:.1f}">t</text>')

    for r in (0.6, 1.2, 1.9, 2.6):
        pts = [(r * math.cos(a), r * math.sin(a)) for a in lin(0, 2 * math.pi)]
        out.append(f'<path class="grid" d="{right.path(pts, close=True)}"/>')
    for k in range(12):
        a = k * math.pi / 6
        out.append(f'<path class="grid" d="{right.path([(0.25*math.cos(a), 0.25*math.sin(a)), (2.75*math.cos(a), 2.75*math.sin(a))])}"/>')
    ou, ov = right(0, 0)
    out.append(f'<circle class="puncture" cx="{ou:.2f}" cy="{ov:.2f}" r="4"/>')
    out.append(f'<text class="lbl-faint" x="{right(-2.75, -2.55)[0]:.1f}" y="{right(0, -2.55)[1]:.1f}">origin omitted</text>')

    # One patch, drawn twice in the domain a full strip apart, once in the image.
    s0, ds, t0, dt = 0.35, 0.22, 1.15, 0.45
    for t in (t0, t0 + 2 * math.pi):
        pts = [(s0 - ds, t - dt), (s0 + ds, t - dt), (s0 + ds, t + dt), (s0 - ds, t + dt)]
        out.append(f'<path class="patch" d="{left.path(pts, close=True)}"/>')
    ring = []
    for i, sv in enumerate((s0 - ds, s0 + ds)):
        arc = [(math.exp(sv) * math.cos(t), math.exp(sv) * math.sin(t)) for t in lin(t0 - dt, t0 + dt, 28)]
        ring += arc if i == 0 else arc[::-1]
    out.append(f'<path class="patch" d="{right.path(ring, close=True)}"/>')

    out.append('<path class="arrow" d="M292 168 L346 168"/>')
    out.append('<path class="arrowhead" d="M346 168 l-6 -3.4 v6.8 Z"/>')
    out.append('<text class="lbl-mark math" x="310" y="160">E</text>')
    out.append(f'<text class="lbl-mark" x="56" y="{h - 12}">the two marked patches lie 2 pi apart and share one image</text>')

    write(
        "exponential-wrap",
        "Strips of height 2pi in the (s,t) plane wrapping onto the punctured plane under E.",
        svg(W, h, "\n".join(out)),
    )


# --------------------------------------------------------------------------
# 3. H(x, y) = (x, xy): the input escapes while the output converges.
# --------------------------------------------------------------------------
def fig_escape():
    h = 300
    out = []
    left = Frame((-0.35, 3.4), (-0.6, 6.4), (56, 58, 215, 200))
    right = Frame((-0.35, 3.4), (-0.6, 2.4), (372, 58, 215, 200))

    out += heading(56, 'input', 'the path (1/t, t) runs off to infinity')
    out += heading(372, 'output', 'its image settles on a finite point')

    for fr, ymax in ((left, 6.4), (right, 2.4)):
        out.append(f'<path class="axis" d="{fr.path([(-0.35, 0), (3.4, 0)])}"/>')
        out.append(f'<path class="axis" d="{fr.path([(0, -0.6), (0, ymax)])}"/>')

    # Input path: x = 1/t, y = t, for t in [0.32, 6.2].
    pts = [(1 / t, t) for t in lin(0.32, 6.2, 260)]
    pts = [(x, y) for x, y in pts if x <= 3.4 and y <= 6.4]
    out.append(f'<path class="curve" d="{left.path(pts)}"/>')
    for t in (0.9, 1.6, 2.8, 5.0):
        u, v = left(1 / t, t)
        out.append(f'<circle class="dot" cx="{u:.2f}" cy="{v:.2f}" r="3.1"/>')
    out.append(f'<text class="math lbl-mark" x="{left(0.55, 4.6)[0]:.1f}" y="{left(0.55, 4.6)[1]:.1f}">xy = 1</text>')

    # Output path: the horizontal segment v = 1, marching toward (0, 1).
    out.append(f'<path class="curve" d="{right.path([(1 / 0.32, 1), (1 / 6.2, 1)])}"/>')
    for t in (0.9, 1.6, 2.8, 5.0):
        u, v = right(min(1 / t, 3.4), 1)
        out.append(f'<circle class="dot" cx="{u:.2f}" cy="{v:.2f}" r="3.1"/>')
    au, av = right(0, 1)
    out.append(f'<circle class="open" cx="{au:.2f}" cy="{av:.2f}" r="4.6"/>')
    out.append(f'<text class="lbl-mark" x="{au + 9:.1f}" y="{av - 18:.1f}">asymptotic value (0, 1)</text>')

    out.append('<path class="arrow" d="M292 158 L352 158"/>')
    out.append('<path class="arrowhead" d="M352 158 l-6 -3.4 v6.8 Z"/>')
    out.append('<text class="lbl-mark math" x="310" y="150">H</text>')
    out.append(footnote(56, h, 'not a Keller map: the Jacobian of H is x, which vanishes along a line'))

    write(
        "escape-to-infinity",
        "The path (1/t, t) escaping to infinity while its image under H(x,y)=(x,xy) converges to (0,1).",
        svg(W, h, "\n".join(out)),
    )


# --------------------------------------------------------------------------
# 4. Monodromy: the two roots of z^2 = w exchange as w circles the origin.
# --------------------------------------------------------------------------
def fig_monodromy():
    h = 322
    out = []
    left = Frame((-1.7, 1.7), (-1.7, 1.7), (56, 62, 200, 200))
    right = Frame((-1.9, 1.9), (-1.4, 1.4), (360, 62, 230, 200))

    out += heading(56, 'an ordinary branch point', 'one loop around 0 swaps the roots of z² = w')
    out += heading(360, 'the hypothetical Keller picture', 'the obstacle is a curve, not a point')

    out.append(f'<path class="axis" d="{left.path([(-1.7, 0), (1.7, 0)])}"/>')
    out.append(f'<path class="axis" d="{left.path([(0, -1.7), (0, 1.7)])}"/>')

    # The two square roots, traced over a half turn each while w does a full turn.
    r = 1.0
    for sign, cls in ((1, "curve"), (-1, "curve-alt")):
        pts = [(sign * math.sqrt(r) * math.cos(a / 2), sign * math.sqrt(r) * math.sin(a / 2))
               for a in lin(0, 2 * math.pi, 120)]
        out.append(f'<path class="{cls}" d="{left.path(pts)}"/>')
        su, sv = left(*pts[0])
        eu, ev = left(*pts[-1])
        out.append(f'<circle class="dot" cx="{su:.2f}" cy="{sv:.2f}" r="3.4"/>')
        out.append(f'<circle class="open" cx="{eu:.2f}" cy="{ev:.2f}" r="4"/>')
    out.append(f'<text class="math lbl-ink" x="{left(1.12, 0.14)[0]:.1f}" y="{left(1.12, 0.14)[1]:.1f}">+√w</text>')
    out.append(f'<text class="math lbl-ink" x="{left(-1.5, -0.22)[0]:.1f}" y="{left(-1.5, -0.22)[1]:.1f}">−√w</text>')
    bu, bv = left(0, 0)
    out.append(f'<circle class="puncture" cx="{bu:.2f}" cy="{bv:.2f}" r="4"/>')

    # Right: an asymptotic curve, a loop around it, and N inverse sheets above.
    curve = [(t, 0.28 * math.sin(1.5 * t) - 0.45) for t in lin(-1.85, 1.85)]
    out.append(f'<path class="curve-heavy" d="{right.path(curve)}"/>')
    out.append(f'<text class="lbl-mark" x="{right(-1.8, -0.95)[0]:.1f}" y="{right(-1.8, -0.95)[1]:.1f}">the non-properness set</text>')
    loop = [(0.55 + 0.34 * math.cos(a), -0.36 + 0.22 * math.sin(a)) for a in lin(0, 2 * math.pi)]
    out.append(f'<path class="loop" d="{right.path(loop, close=True)}"/>')
    for k in range(4):
        yy = 0.42 + 0.24 * k
        arc = [(t, yy + 0.05 * math.sin(2.2 * t)) for t in lin(-0.1, 1.25, 40)]
        out.append(f'<path class="sheet" d="{right.path(arc)}"/>')
    out.append(f'<text class="lbl-faint" x="{right(1.32, 0.95)[0]:.1f}" y="{right(1.32, 0.95)[1]:.1f}">N sheets</text>')
    out.append(f'<text class="lbl-faint" x="{right(-1.85, 1.15)[0]:.1f}" y="{right(-1.85, 1.15)[1]:.1f}">local inverses over the loop</text>')

    write(
        "monodromy",
        "Root exchange for z^2 = w beside a schematic of inverse sheets over a loop around the asymptotic curve.",
        svg(W, h, "\n".join(out)),
    )


# --------------------------------------------------------------------------
# 5. The Newton polygon of y^2 - x^3 - x, and the curve it predicts.
# --------------------------------------------------------------------------
def fig_newton():
    h = 336
    out = []
    left = Frame((-0.55, 3.6), (-0.55, 2.6), (96, 66, 285, 190))
    right = Frame((-1.4, 3.1), (-6.0, 6.0), (510, 66, 285, 190))

    out += heading(96, 'exponents', 'the monomials of y² − x³ − x, and their hull')
    out += heading(510, 'the curve', 'a real slice of y² = x³ + x, against y = ±x^{3/2}')

    # Lattice.
    for i in range(4):
        for j in range(3):
            u, v = left(i, j)
            out.append(f'<circle class="lattice" cx="{u:.2f}" cy="{v:.2f}" r="1.4"/>')
    out.append(f'<path class="axis" d="{left.path([(-0.4, 0), (3.5, 0)])}"/>')
    out.append(f'<path class="axis" d="{left.path([(0, -0.4), (0, 2.5)])}"/>')
    out.append(f'<text class="math lbl-ink" x="{left(3.4, 0)[0]:.1f}" y="{left(0, 0)[1] + 20:.1f}">i</text>')
    out.append(f'<text class="math lbl-ink" x="{left(0, 0)[0] - 18:.1f}" y="{left(0, 2.4)[1]:.1f}">j</text>')

    # Hull of {(0,2), (3,0), (1,0)}.
    hull = [(0, 2), (3, 0), (1, 0)]
    out.append(f'<path class="hull" d="{left.path(hull, close=True)}"/>')
    # The edge that sets the balance 2r = 3.
    out.append(f'<path class="edge" d="{left.path([(0, 2), (3, 0)])}"/>')
    for (i, j), lbl in (((0, 2), "y²"), ((3, 0), "x³"), ((1, 0), "x")):
        u, v = left(i, j)
        out.append(f'<circle class="dot" cx="{u:.2f}" cy="{v:.2f}" r="4.2"/>')
        out.append(f'<text class="math lbl-ink" x="{u + 9:.1f}" y="{v - 8:.1f}">{lbl}</text>')
    mu, mv = left(1.5, 1.0)
    out.append(f'<text class="lbl-mark" x="{mu + 12:.1f}" y="{mv - 4:.1f}">slope −⅔ → r = 3/2</text>')

    # The curve y^2 = x^3 + x, real slice, and its leading approximation.
    upper = [(x, math.sqrt(x ** 3 + x)) for x in lin(0, 3.05, 300)]
    out.append(f'<path class="curve-heavy" d="{right.path(upper)}"/>')
    out.append(f'<path class="curve-heavy" d="{right.path([(x, -y) for x, y in upper])}"/>')
    approx = [(x, x ** 1.5) for x in lin(0, 3.05, 300)]
    out.append(f'<path class="dashed" d="{right.path(approx)}"/>')
    out.append(f'<path class="dashed" d="{right.path([(x, -y) for x, y in approx])}"/>')
    out.append(f'<path class="axis" d="{right.path([(-1.3, 0), (3.05, 0)])}"/>')
    out.append(f'<path class="axis" d="{right.path([(0, -5.8), (0, 5.8)])}"/>')
    out.append(f'<text class="math lbl-ink" x="{right(2.05, 4.45)[0]:.1f}" y="{right(2.05, 4.45)[1]:.1f}">y² = x³ + x</text>')
    out.append(f'<text class="lbl-mark math" x="{right(1.55, -4.3)[0]:.1f}" y="{right(1.55, -4.3)[1]:.1f}">y = ±x^(3/2)</text>')
    out.append(footnote(510, h, 'the two agree to leading order and separate below it'))

    write(
        "newton-polygon",
        "The Newton polygon of y^2 - x^3 - x beside the real slice of the curve and its leading approximation.",
        svg(WIDE, h, "\n".join(out), extra=' preserveAspectRatio="xMidYMid meet"'),
    )


# --------------------------------------------------------------------------
# 6. Theorem A: which degree pairs (deg A, deg C) can solve AC' - vA'C = c.
# --------------------------------------------------------------------------
def fig_degree_lattice():
    nu = 2
    h = 340
    out = []
    fr = Frame((-0.7, 5.5), (-0.9, 10.7), (96, 62, 330, 246))
    LX = 476  # the legend column

    out += heading(96, f'degree pairs', f'which (deg A, deg C) can solve the identity, shown for nu = {nu}')

    for i in range(6):
        for j in range(11):
            u, v = fr(i, j)
            out.append(f'<circle class="lattice" cx="{u:.2f}" cy="{v:.2f}" r="1.5"/>')

    out.append(f'<path class="axis" d="{fr.path([(-0.5, 0), (5.4, 0)])}"/>')
    out.append(f'<path class="axis" d="{fr.path([(0, -0.6), (0, 10.5)])}"/>')
    out.append(f'<text class="math lbl-ink" x="{fr(5.0, 0)[0]:.1f}" y="{fr(0, 0)[1] + 20:.1f}">deg A</text>')
    out.append(f'<text class="math lbl-ink" x="{fr(0.12, 0)[0]:.1f}" y="{fr(0, 10.4)[1]:.1f}">deg C</text>')

    # The cancellation line deg C = v deg A.
    out.append(f'<path class="dashed" d="{fr.path([(0, 0), (5.3, nu * 5.3)])}"/>')

    # The reduction walks straight down off that line.
    a0, top, bot = 3, nu * 3, 1
    out.append(f'<path class="arrow" d="{fr.path([(a0, top - 0.3), (a0, bot + 0.5)])}"/>')
    au, av = fr(a0, bot + 0.5)
    out.append(f'<path class="arrowhead" d="M{au:.2f} {av:.2f} l-3.4 -6 h6.8 Z"/>')
    for j, cls, r in ((top, "dot", 3.6), (bot, "open", 4.2)):
        u, v = fr(a0, j)
        out.append(f'<circle class="{cls}" cx="{u:.2f}" cy="{v:.2f}" r="{r}"/>')

    # deg A + deg C = 1, and the only two lattice points on it.
    out.append(f'<path class="curve" d="{fr.path([(-0.45, 1.45), (1.45, -0.45)])}"/>')
    for (i, j) in ((0, 1), (1, 0)):
        u, v = fr(i, j)
        out.append(f'<circle class="solution" cx="{u:.2f}" cy="{v:.2f}" r="5"/>')

    # Legend, set clear of the drawing so nothing has to be crammed inside it.
    rows = [
        ("dashed", f"deg C = {nu} x deg A"),
        (None, "the leading terms cancel here"),
        ("arrow", f"subtract a multiple of A^{nu}"),
        (None, "moves straight down, changes nothing"),
        ("solution", "deg A + deg C = 1"),
        (None, "the only pairs that survive"),
    ]
    y = 96
    for mark, text in rows:
        if mark == "dashed":
            out.append(f'<path class="dashed" d="M{LX} {y - 4} h22"/>')
        elif mark == "arrow":
            out.append(f'<path class="arrow" d="M{LX + 11} {y - 13} v16"/>')
            out.append(f'<path class="arrowhead" d="M{LX + 11} {y + 4} l-3.4 -6 h6.8 Z"/>')
        elif mark == "solution":
            out.append(f'<circle class="solution" cx="{LX + 11}" cy="{y - 4}" r="5"/>')
        cls = "lbl-ink" if mark else "lbl-faint"
        out.append(f'<text class="{cls}" x="{LX + 34}" y="{y}">{text}</text>')
        y += 18 if mark is None else 16
        if mark is None:
            y += 12

    out.append(footnote(96, h, 'off the dashed line the leading terms survive, so the degree must fall to zero'))

    write(
        "degree-lattice",
        "Degree pairs (deg A, deg C) admissible for AC' - vA'C = c, with the reduction arrow.",
        svg(WIDE, h, "\n".join(out), extra=' preserveAspectRatio="xMidYMid meet"'),
    )


# --------------------------------------------------------------------------
# 7. Vertex gap: narrow supports, and a Minkowski vertex with one decomposition.
# --------------------------------------------------------------------------
def fig_vertex_gap():
    h = 330
    out = []
    lo, hi = -0.55, 4.6
    left = Frame((lo, hi), (lo, hi), (96, 66, 240, 220))
    right = Frame((lo, hi), (lo, hi), (516, 66, 240, 220))

    def lattice(fr):
        g = []
        for i in range(5):
            for j in range(5):
                u, v = fr(i, j)
                g.append(f'<circle class="lattice" cx="{u:.2f}" cy="{v:.2f}" r="2"/>')
        g.append(f'<path class="axis" d="{fr.path([(lo, 0), (hi, 0)])}"/>')
        g.append(f'<path class="axis" d="{fr.path([(0, lo), (0, hi)])}"/>')
        return g

    # Panel 1: the two strips, both narrow in the direction w = 2i - j.
    out += heading(96, 'narrow supports', 'every exponent sits in a thin band of w = 2i - j')
    # Q occupies 0 <= w <= 3, P the narrower 0 <= w <= 2.
    out.append(f'<path class="strip-b" d="{left.path([(-0.25, lo), (2.3, hi), (3.8, hi), (1.3, lo)], close=True)}"/>')
    out.append(f'<path class="strip-a" d="{left.path([(-0.25, lo), (2.3, hi), (3.3, hi), (0.8, lo)], close=True)}"/>')
    out += lattice(left)
    out.append(f'<path class="guide" d="{left.path([(-0.25, lo), (2.3, hi)])}"/>')
    for (i, j), lbl, cls in (((1, 0), "a1", "dot"), ((2, 1), "b3", "dot")):
        u, v = left(i, j)
        out.append(f'<circle class="{cls}" cx="{u:.2f}" cy="{v:.2f}" r="4"/>')
        out.append(f'<text class="lbl-mark" x="{u + 7:.1f}" y="{v - 7:.1f}">{lbl}</text>')
    out.append(f'<text class="lbl-faint" x="{left(0.15, 4.4)[0]:.1f}" y="{left(0, 4.4)[1]:.1f}">w = 0</text>')
    pu, pv = left(2.05, 3.5)
    out.append(f'<text class="lbl-faint" x="{pu:.1f}" y="{pv:.1f}">P: 0 to 2</text>')
    qu, qv = left(3.0, 3.0)
    out.append(f'<text class="lbl-faint" x="{qu:.1f}" y="{qv:.1f}">Q: 0 to 3</text>')
    out.append(f'<text class="math lbl-ink" x="{left(4.3, 0)[0]:.1f}" y="{left(0, 0)[1] + 20:.1f}">i</text>')
    out.append(f'<text class="math lbl-ink" x="{left(0, 0)[0] - 16:.1f}" y="{left(0, 4.4)[1]:.1f}">j</text>')

    # Panel 2: the Minkowski point that carries x-squared is a vertex.
    out += heading(516, 'one decomposition', 'the corner (3,1) splits in only one way')
    out += lattice(right)
    out.append(f'<path class="arrow" d="{right.path([(0, 0), (0.92, 0)])}"/>')
    au, av = right(0.92, 0)
    out.append(f'<path class="arrowhead" d="M{au:.2f} {av:.2f} l-6 -3.4 v6.8 Z"/>')
    out.append(f'<path class="arrow" d="{right.path([(1.06, 0.03), (2.92, 0.96)])}"/>')
    bu, bv = right(2.92, 0.96)
    out.append(f'<path class="arrowhead" d="M{bu:.2f} {bv:.2f} l-6.4 -1.2 l2.6 5.4 Z"/>')
    for (i, j), lbl in (((1, 0), "p0 = (1,0)"), ((2, 1), "")):
        if not lbl:
            continue
        u, v = right(i, j)
        out.append(f'<text class="lbl-mark" x="{u - 14:.1f}" y="{v + 20:.1f}">{lbl}</text>')
    mu, mv = right(1.9, 0.35)
    out.append(f'<text class="lbl-mark" x="{mu:.1f}" y="{mv:.1f}">q0 = (2,1)</text>')
    vu, vv = right(3, 1)
    out.append(f'<circle class="solution" cx="{vu:.2f}" cy="{vv:.2f}" r="6"/>')
    out.append(f'<text class="lbl-ink" x="{vu + 10:.1f}" y="{vv - 8:.1f}">(3,1)</text>')
    out.append(f'<text class="lbl-faint" x="{vu + 10:.1f}" y="{vv + 5:.1f}">carries x squared</text>')
    eu, ev = right(0.25, 2.5)
    out.append(f'<text class="lbl-ink" x="{eu:.1f}" y="{ev:.1f}">one term, so</text>')
    out.append(f'<text class="lbl-mark" x="{eu:.1f}" y="{ev + 15:.1f}">a1 · b3 = 1</text>')

    out.append(footnote(96, h, 'a corner has only one decomposition, so the sum collapses to a single product'))

    write(
        "vertex-gap",
        "Narrow exponent strips, and the unique decomposition of the Minkowski vertex (3,1).",
        svg(WIDE, h, "\n".join(out), extra=' preserveAspectRatio="xMidYMid meet"'),
    )


# --------------------------------------------------------------------------
# 8. The cubic Kummer picture: three conjugate roots, and what their
#    permutation leaves alone.
# --------------------------------------------------------------------------
def fig_cube_root():
    h = 320
    out = []
    fr = Frame((-1.75, 1.75), (-1.75, 1.75), (118, 66, 200, 200))

    out += heading(96, 'three conjugate roots', 'the deck map turns each cube root into the next')

    circle = [(math.cos(a), math.sin(a)) for a in lin(0, 2 * math.pi)]
    out.append(f'<path class="grid" d="{fr.path(circle, close=True)}"/>')
    out.append(f'<path class="axis" d="{fr.path([(-1.5, 0), (1.5, 0)])}"/>')
    out.append(f'<path class="axis" d="{fr.path([(0, -1.5), (0, 1.5)])}"/>')

    roots = [math.pi / 2, math.pi / 2 + 2 * math.pi / 3, math.pi / 2 + 4 * math.pi / 3]
    labels = ["t", "ωt", "ω²t"]
    for a, lbl in zip(roots, labels):
        u, v = fr(math.cos(a), math.sin(a))
        out.append(f'<circle class="dot" cx="{u:.2f}" cy="{v:.2f}" r="4.5"/>')
        lu, lv = fr(1.34 * math.cos(a), 1.34 * math.sin(a))
        out.append(f'<text class="math lbl-ink" x="{lu - 6:.1f}" y="{lv + 4:.1f}">{lbl}</text>')

    # Arcs carrying each root to the next.
    for a in roots:
        arc = [(1.0 * math.cos(th), 1.0 * math.sin(th))
               for th in lin(a + 0.28, a + 2 * math.pi / 3 - 0.28, 30)]
        out.append(f'<path class="deck" d="{fr.path(arc)}"/>')
        eu, ev = fr(*arc[-1])
        pu, pv = fr(*arc[-3])
        dx, dy = eu - pu, ev - pv
        n = math.hypot(dx, dy) or 1
        dx, dy = dx / n * 6, dy / n * 6
        out.append(f'<path class="arrowhead" d="M{eu:.2f} {ev:.2f} l{-dx - dy * 0.5:.2f} {-dy + dx * 0.5:.2f} l{dy:.2f} {-dx:.2f} Z"/>')
    hu, hv = fr(-1.62, -1.5)
    out.append(f'<text class="math lbl-faint" x="{hu:.1f}" y="{hv:.1f}">t³ = H</text>')

    # The weight ledger: powers of t sorted by their eigenvalue under the map.
    CX = [452, 588, 716]
    out += heading(452, 'what survives', 'powers of t, sorted by how the deck map scales them')
    heads = ["weight 0", "weight 1", "weight 2"]
    rows = [["1", "t", "t²"], ["t³ = H", "t⁴", "t⁵"], ["t⁶ = H²", "t⁷", "t⁸"]]
    out.append(f'<path class="edge" d="M{CX[0] - 12} 76 v104"/>')
    for c, head in enumerate(heads):
        out.append(f'<text class="{"lbl-ink" if c == 0 else "lbl-faint"} ttl" x="{CX[c]}" y="88">{head}</text>')
    for r, row in enumerate(rows):
        for c, cell in enumerate(row):
            cls = "lbl-ink" if c == 0 else "lbl-faint"
            out.append(f'<text class="math {cls}" x="{CX[c]}" y="{114 + r * 22}">{cell}</text>')
    out.append(f'<text class="lbl-mark" x="{CX[0] - 12}" y="200">fixed by the map,</text>')
    out.append(f'<text class="lbl-mark" x="{CX[0] - 12}" y="214">so already in k(x)</text>')
    out.append(f'<text class="math lbl-faint" x="{CX[1]}" y="202">scaled by ω</text>')
    out.append(f'<text class="math lbl-faint" x="{CX[2]}" y="202">scaled by ω²</text>')

    out.append(footnote(96, h, 'an equation can only mention weight 0 if it is to descend to the base field'))

    write(
        "cube-root",
        "The three cube roots of H, the deck action permuting them, and the weight grading it induces.",
        svg(WIDE, h, "\n".join(out), extra=' preserveAspectRatio="xMidYMid meet"'),
    )


# --------------------------------------------------------------------------
# 9. The census never empties: three unbounded families of admissible skeletons.
#    Data from AUDIT.md integration #17 deltas (n) and (w).
# --------------------------------------------------------------------------
def fig_census_rays():
    h = 340
    out = []
    fr = Frame((0, 830), (0, 74), (96, 62, 470, 240))
    LX = 612

    out.append('<text class="lbl-ink ttl" x="96" y="30">three unbounded families</text>')
    out.append('<text x="96" y="46">every member passes all thirteen of Moh\'s printed conditions</text>')

    # Axes and ticks.
    out.append(f'<path class="axis" d="{fr.path([(0, 0), (830, 0)])}"/>')
    out.append(f'<path class="axis" d="{fr.path([(0, 0), (0, 74)])}"/>')
    for n in (200, 400, 600, 800):
        u, v = fr(n, 0)
        out.append(f'<path class="axis" d="M{u:.1f} {v:.1f} v4"/>')
        out.append(f'<text x="{u - 10:.1f}" y="{v + 16:.1f}">{n}</text>')
    for N in (20, 40, 60):
        u, v = fr(0, N)
        out.append(f'<path class="axis" d="M{u - 4:.1f} {v:.1f} h4"/>')
        out.append(f'<text x="{u - 24:.1f}" y="{v + 4:.1f}">{N}</text>')
    out.append(f'<text class="math lbl-ink" x="{fr(745, 0)[0]:.1f}" y="{fr(0, 0)[1] - 8:.1f}">n = deg g</text>')
    out.append(f'<text class="math lbl-ink" x="{fr(0, 0)[0] + 6:.1f}" y="{fr(0, 72)[1] - 2:.1f}">N</text>')

    sol = [(168 * a + 105, 15 * a + 9) for a in range(5)]         # L = 8a+5
    a26 = [(9 * (7 * t + 6), 6) for t in range(6)]                # A2 = 6 ray
    k16 = [(48 * t + 16, 6 * t + 3) for t in range(1, 9)]         # K = 16 ray

    for pts in (sol, a26, k16):
        out.append(f'<path class="guide" d="{fr.path([pts[0], pts[-1]])}"/>')
    for x, y in sol:
        u, v = fr(x, y); out.append(f'<circle class="dot" cx="{u:.2f}" cy="{v:.2f}" r="3.6"/>')
    for x, y in a26:
        u, v = fr(x, y); out.append(f'<circle class="solution" cx="{u:.2f}" cy="{v:.2f}" r="4"/>')
    for x, y in k16:
        u, v = fr(x, y); out.append(f'<rect class="sqr" x="{u - 3:.2f}" y="{v - 3:.2f}" width="6" height="6"/>')

    # Legend.
    y = 96
    # Tiers live in the caption, where there is room to say them properly.
    rows = [
        ("dot", "L = 8a + 5 ray"), (None, "n = 21L, N = 15a + 9"),
        ("solution", "A2 = 6 ray"), (None, "n = 9(7t + 6), N = 6 for all t"),
        ("sqr", "K = 16 ray"), (None, "n = 48t + 16, N = 6t + 3"),
    ]
    for mark, text in rows:
        if mark == "dot":
            out.append(f'<circle class="dot" cx="{LX + 8}" cy="{y - 4}" r="3.6"/>')
        elif mark == "solution":
            out.append(f'<circle class="solution" cx="{LX + 8}" cy="{y - 4}" r="4"/>')
        elif mark == "sqr":
            out.append(f'<rect class="sqr" x="{LX + 5}" y="{y - 7}" width="6" height="6"/>')
        out.append(f'<text class="{"lbl-ink" if mark else "lbl-faint"}" x="{LX + 26}" y="{y}">{text}</text>')
        y += 16 if mark else 26

    out.append(f'<text class="lbl-faint" x="96" y="{h - 14}">no degree is the last one, so no ceiling can come from the numerical skeleton alone</text>')
    write(
        "census-rays",
        "Three unbounded families of Moh-admissible skeletons, geometric degree N against n.",
        svg(WIDE, h, "\n".join(out), extra=' preserveAspectRatio="xMidYMid meet"'),
    )


# --------------------------------------------------------------------------
# 10. The trace test: deg_x of Tr(f^(k+1)) on a Keller pair and on a control.
#     Data computed by sympy on (x+y^2, y+(x+y^2)^3) and (x+y^2, y^3+xy).
# --------------------------------------------------------------------------
def fig_trace_degrees():
    h = 300
    out = []
    fr = Frame((-0.5, 5.6), (-0.6, 6.9), (76, 60, 270, 196))
    keller = [0, 0, 0, 0, 0, 1]
    control = [1, 2, 3, 4, 5, 6]

    out.append('<text class="lbl-ink ttl" x="76" y="30">trace degrees</text>')
    out.append('<text x="76" y="46">the x-degree of Tr(f^(k+1)), for k = 0 to 5</text>')

    out.append(f'<path class="axis" d="{fr.path([(-0.3, 0), (5.5, 0)])}"/>')
    out.append(f'<path class="axis" d="{fr.path([(0, -0.3), (0, 6.6)])}"/>')
    for k in range(6):
        u, v = fr(k, 0)
        out.append(f'<text x="{u - 3:.1f}" y="{v + 16:.1f}">{k}</text>')
    for d in (2, 4, 6):
        u, v = fr(0, d)
        out.append(f'<text x="{u - 20:.1f}" y="{v + 4:.1f}">{d}</text>')
    out.append(f'<text class="math lbl-ink" x="{fr(5.1, 0)[0]:.1f}" y="{fr(0, 0)[1] + 32:.1f}">k</text>')

    pts = [(k, d) for k, d in enumerate(control)]
    out.append(f'<path class="curve" d="{fr.path(pts)}"/>')
    for k, d in pts:
        u, v = fr(k, d); out.append(f'<circle class="dot" cx="{u:.2f}" cy="{v:.2f}" r="3.4"/>')
    kp = [(k, d) for k, d in enumerate(keller)]
    out.append(f'<path class="dashed" d="{fr.path(kp)}"/>')
    for k, d in kp:
        u, v = fr(k, d); out.append(f'<circle class="solution" cx="{u:.2f}" cy="{v:.2f}" r="4"/>')

    LX = 392
    out.append(f'<path class="curve" d="M{LX} 98 h18"/><circle class="dot" cx="{LX + 9}" cy="98" r="3.4"/>')
    out.append(f'<text class="lbl-ink" x="{LX + 28}" y="102">not Keller: grows with k</text>')
    out.append(f'<text class="math lbl-faint" x="{LX + 28}" y="118">(x + y², y³ + xy)</text>')
    out.append(f'<path class="dashed" d="M{LX} 150 h18"/><circle class="solution" cx="{LX + 9}" cy="150" r="4"/>')
    out.append(f'<text class="lbl-ink" x="{LX + 28}" y="154">Keller: stays on the floor</text>')
    out.append(f'<text class="math lbl-faint" x="{LX + 28}" y="170">(x + y², y + (x + y²)³)</text>')

    out.append(f'<text class="lbl-faint" x="76" y="{h - 14}">the k = 0 point is already a Keller test: a constant Jacobian makes Tr(f) free of x</text>')
    write(
        "trace-degrees",
        "deg_x of Tr(f^(k+1)) for a Keller automorphism and a non-Keller control.",
        svg(W, h, "\n".join(out)),
    )


# --------------------------------------------------------------------------
# 11. Moh's descent: a pair of degrees (n, m) with u_s = 1 falls to (n/d_s, m/d_s).
#     Rows from Moh p.207 and from AUDIT.md deltas 17(t), 17(w).
# --------------------------------------------------------------------------
def fig_descent():
    h = 340
    out = []
    fr = Frame((0, 178), (0, 128), (96, 62, 420, 240))
    LX = 566

    out.append('<text class="lbl-ink ttl" x="96" y="30">descent</text>')
    out.append('<text x="96" y="46">each pair falls along its own ray through the origin, divided by d_s</text>')

    out.append(f'<path class="axis" d="{fr.path([(0, 0), (175, 0)])}"/>')
    out.append(f'<path class="axis" d="{fr.path([(0, 0), (0, 125)])}"/>')
    out.append(f'<text class="math lbl-ink" x="{fr(168, 0)[0]:.1f}" y="{fr(0, 0)[1] - 8:.1f}">n</text>')
    out.append(f'<text class="math lbl-ink" x="{fr(0, 0)[0] - 14:.1f}" y="{fr(0, 121)[1]:.1f}">m</text>')

    # The K = 16 ray and its descended image, both through the origin's direction.
    out.append(f'<path class="guide" d="{fr.path([(0, 0), (172, 172 * 2 / 3)])}"/>')

    arrows = [((64, 48), (16, 12), "4"), ((84, 56), (21, 14), "4"), ((75, 50), (15, 10), "5"),
              ((112, 80), (28, 20), "4"), ((160, 112), (40, 28), "4"),
              ((105, 70), (15, 10), "7"), ((105, 70), (21, 14), "5")]
    for (n0, m0), (n1, m1), d in arrows:
        # Stop short of the child so the head does not sit on the marker.
        t = 0.93
        end = (n1 + (n0 - n1) * (1 - t), m1 + (m0 - m1) * (1 - t))
        out.append(f'<path class="arrow" d="{fr.path([(n0, m0), end])}"/>')
        eu, ev = fr(*end); su, sv = fr(n0, m0)
        dx, dy = eu - su, ev - sv; L = math.hypot(dx, dy) or 1; dx, dy = dx / L * 7, dy / L * 7
        out.append(f'<path class="arrowhead" d="M{eu:.2f} {ev:.2f} l{-dx + dy * 0.45:.2f} {-dy - dx * 0.45:.2f} l{-dy * 0.9:.2f} {dx * 0.9:.2f} Z"/>')
        mu, mv = fr((n0 + n1) / 2, (m0 + m1) / 2)
        side = 1 if (n0 + m0) % 2 else -1
        out.append(f'<text class="lbl-mark" x="{mu + 5 * side + 2:.1f}" y="{mv - 9 * side + 3:.1f}">÷{d}</text>')
    parents = {(64, 48), (84, 56), (75, 50), (112, 80), (160, 112), (105, 70)}
    children = {(16, 12), (21, 14), (15, 10), (28, 20), (40, 28)}
    above = {(64, 48): False, (84, 56): True, (75, 50): False, (112, 80): True, (160, 112): True, (105, 70): False}
    for n0, m0 in parents:
        u, v = fr(n0, m0); out.append(f'<circle class="dot" cx="{u:.2f}" cy="{v:.2f}" r="3.8"/>')
        dy = -8 if above[(n0, m0)] else 14
        out.append(f'<text class="lbl-faint" x="{u + 7:.1f}" y="{v + dy:.1f}">({n0},{m0})</text>')
    for n1, m1 in children:
        u, v = fr(n1, m1); out.append(f'<circle class="solution" cx="{u:.2f}" cy="{v:.2f}" r="4.2"/>')

    y = 96
    rows = [("dot", "parent pair (n, m)"), ("solution", "child pair (n/d_s, m/d_s)"),
            (None, ""), ("guide", "the K = 16 ray, n : m = 3 : 2"),
            (None, "t = 1 is (64, 48), t = 2 is (112, 80)"),
            (None, ""), (None, "(105, 70) descends two ways,"), (None, "to (15, 10) and to (21, 14)")]
    for mark, text in rows:
        if mark == "dot": out.append(f'<circle class="dot" cx="{LX + 8}" cy="{y - 4}" r="3.8"/>')
        elif mark == "solution": out.append(f'<circle class="solution" cx="{LX + 8}" cy="{y - 4}" r="4.2"/>')
        elif mark == "guide": out.append(f'<path class="guide" d="M{LX} {y - 4} h18"/>')
        if text: out.append(f'<text class="{"lbl-ink" if mark else "lbl-faint"}" x="{LX + 26}" y="{y}">{text}</text>')
        y += 18 if text else 8

    out.append(f'<text class="lbl-faint" x="96" y="{h - 14}">the children have a monomial Jacobian, and live where the campaign already holds certificates</text>')
    write(
        "descent",
        "Moh's descent: parent degree pairs falling to their descended pairs along rays through the origin.",
        svg(WIDE, h, "\n".join(out), extra=' preserveAspectRatio="xMidYMid meet"'),
    )


# --------------------------------------------------------------------------
# 12. Galois orbits of discs, and the screen they license.
#     Counts from AUDIT.md 17(ggggggggggg) and the 2026-09-05 LIVE STATE.
# --------------------------------------------------------------------------
def fig_orbit_screen():
    h = 340
    out = []

    out.append('<text class="lbl-ink ttl" x="96" y="30">one tower</text>')
    out.append('<text x="96" y="46">the deck action rotates the discs below each split</text>')
    # A schematic s = 3 tower: D3 splits into a major and a minor child; the
    # major child splits into A2 conjugate bottom discs forming one orbit.
    D3 = (236, 92); D2 = (176, 158); D2m = (316, 158)
    bottoms = [(96 + 52 * i, 232) for i in range(4)]
    minor_child = (316, 232)
    for a, b in ((D3, D2), (D3, D2m), (D2m, minor_child)):
        out.append(f'<path class="link" d="M{a[0]} {a[1]} L{b[0]} {b[1]}"/>')
    for b in bottoms:
        out.append(f'<path class="link" d="M{D2[0]} {D2[1]} L{b[0]} {b[1]}"/>')
    for (cx, cy), r in ((D3, 9), (D2, 8), (D2m, 7)):
        out.append(f'<circle class="node" cx="{cx}" cy="{cy}" r="{r}"/>')
    for cx, cy in bottoms:
        out.append(f'<circle class="dot" cx="{cx}" cy="{cy}" r="4.5"/>')
    out.append(f'<circle class="node" cx="{minor_child[0]}" cy="{minor_child[1]}" r="4.5"/>')
    # The orbit: an arc through the four conjugate bottoms.
    out.append(f'<path class="deck" d="M{bottoms[0][0] - 14} {bottoms[0][1] + 16} Q {(bottoms[0][0] + bottoms[-1][0]) / 2} {bottoms[0][1] + 44} {bottoms[-1][0] + 14} {bottoms[-1][1] + 16}"/>')
    out.append(f'<text class="math lbl-ink" x="{D3[0] + 14}" y="{D3[1] + 4}">D₃</text>')
    out.append(f'<text class="math lbl-ink" x="{D2[0] - 30}" y="{D2[1] + 4}">D₂</text>')
    out.append(f'<text class="lbl-faint" x="{D2m[0] + 12}" y="{D2m[1] + 4}">minor</text>')
    out.append(f'<text class="lbl-mark" x="{D2[0] + 52}" y="{D2[1] + 32}">a (10) level</text>')
    out.append(f'<text class="lbl-mark" x="{D2[0] + 52}" y="{D2[1] + 46}">ω₂ = A₂</text>')
    out.append(f'<text class="lbl-faint" x="{D2m[0] + 12}" y="{D2m[1] + 78}">an (11) level: ω = 1</text>')
    out.append(f'<text class="lbl-mark" x="{bottoms[0][0] - 10}" y="{bottoms[0][1] + 60}">one orbit of bottom discs, |O| = A₂</text>')

    # The screen as a funnel, log scale.
    FX, FW = 520, 300
    out.append('<text class="lbl-ink ttl" x="520" y="30">the screen at n ≤ 200</text>')
    out.append('<text x="520" y="46">necessary configurations after each theorem</text>')
    counts = [(24063, "printed (1) to (13) rows", "lbl-faint"),
              (1420, "coarse stabilizer", "lbl-faint"),
              (90, "actual stabilizer: theorem", "lbl-ink"),
              (64, "full conjunction, with Xu", "lbl-ink")]
    top = math.log10(24063)
    y = 82
    for c, lbl, cls in counts:
        w = FW * math.log10(c) / top
        bar = "bar-mark" if c <= 90 else "bar"
        out.append(f'<rect class="{bar}" x="{FX}" y="{y}" width="{w:.1f}" height="22"/>')
        out.append(f'<text class="lbl-ink" x="{FX + 6}" y="{y + 15}">{c:,}</text>')
        out.append(f'<text class="{cls}" x="{FX}" y="{y + 38}">{lbl}</text>')
        y += 58
    out.append(f'<text class="lbl-faint" x="96" y="{h - 14}">at n ≤ 100 the actual screen keeps exactly the six rows Moh printed in 1983</text>')
    write(
        "orbit-screen",
        "A Galois orbit of bottom discs in one tower, and the funnel of necessary configurations at n <= 200.",
        svg(WIDE, h, "\n".join(out), extra=' preserveAspectRatio="xMidYMid meet"'),
    )


if __name__ == "__main__":
    print("generating figures ->", OUT)
    fig_shear()
    fig_wrap()
    fig_escape()
    fig_monodromy()
    fig_newton()
    fig_degree_lattice()
    fig_vertex_gap()
    fig_cube_root()
    fig_census_rays()
    fig_trace_degrees()
    fig_descent()
    fig_orbit_screen()
